include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "script/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
    weight-of-class: 0.33
    maintainability-index: 50
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics-exclude:
    - test/**
  rules:
    - always-remove-listener
    - avoid-unused-parameters
    - avoid-unnecessary-setstate
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - prefer-conditional-expressions
    - prefer-intl-name
    - provide-correct-intl-args
    - avoid-returning-widgets: false
    - member-ordering-extended:
        alphabetize: false
        order:
          - named-constructors
          - factory-constructors
          - constructors
          - private-static-const-fields
          - public-static-const-fields
          - public-static-final-fields
          - public-static-fields
          - private-static-fields
          - public-final-fields
          - private-final-fields
          - public-fields
          - public-getters-setters
          - private-fields
          - private-getters-setters
          - overridden-methods
          - public-static-methods
          - public-methods
          - protected-methods
          - private-static-methods
          - private-methods

linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    always_use_package_imports: true
    avoid_multiple_declarations_per_line: fasle
    avoid-returning-widgets: false
