name: places
description: places project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.5.0
  dart_code_metrics: ^4.12.0

fonts:
  - family: Roboto
    fonts:
      - asset: assets/fonts/